runtime: python37
entrypoint: gunicorn -b :$PORT wsgi:app
env: standard
instance_class: F1
default_expiration: "1m"

handlers:
-   url: /static
    static_dir: static/
    secure: always
    expiration: '5m'

automatic_scaling:
    min_instances: 0
    max_instances: 1